"""
Embedding Population and Migration Utility for SIH26108 (Phase 10B - Chunk 3).

Populates the PostgreSQL standard_embeddings table using standard records loaded from the repository
and vector embeddings generated by the existing SemanticEmbeddingEngine.
Provides idempotent upsert execution, strict vector dimension validation, atomic transaction management, and explicit CLI execution.
"""

import sys
import numpy as np
from typing import List, Dict, Any, Optional
from sqlalchemy.orm import Session
from sqlalchemy.exc import SQLAlchemyError

from backend.database.connection import (
    Base,
    get_db_engine,
    get_session_factory,
    check_database_connection
)
from backend.database.models import StandardModel, StandardEmbeddingModel
from backend.models.schemas import IndianStandardRecord
from backend.retrieval.text_prep import prepare_document_text
from backend.retrieval.embeddings import SemanticEmbeddingEngine
from backend.config import (
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_EMBEDDING_DIMENSION,
    DATABASE_URL,
    VECTOR_BACKEND
)
from backend.utils.logger import get_logger



logger = get_logger("SeedEmbeddings")


def build_embedding_content(standard: Dict[str, Any]) -> str:
    """
    Constructs a unified, comprehensive text string from standard record fields for embedding generation.
    Returns empty string if input standard is invalid or lacks text content.
    """
    if not isinstance(standard, dict):
        return ""
    
    # Reuse text_prep standard text builder
    text = prepare_document_text(standard).strip()
    
    # Append extended description if available
    desc = standard.get("description")
    if desc and isinstance(desc, str) and desc.strip():
        text = f"{text} {desc.strip()}"

    return text.strip()


def seed_embeddings(
    standards: Optional[List[Dict[str, Any]]] = None,
    engine: Optional[Any] = None,
    session_factory: Optional[Any] = None,
    embedding_engine: Optional[SemanticEmbeddingEngine] = None
) -> Dict[str, Any]:
    """
    Generates semantic vector embeddings for standards using SemanticEmbeddingEngine
    and populates/upserts them into the standard_embeddings database table.

    Params:
        standards: Optional list of standard dictionaries (defaults to repo.get_all_standards())
        engine: SQLAlchemy engine to use
        session_factory: Custom session factory (e.g. for testing)
        embedding_engine: Custom SemanticEmbeddingEngine instance (e.g. for testing)

    Returns:
        Dict execution summary with counts: standards_processed, valid_standards, embeddings_generated, inserted, updated, skipped, failed, total_in_db.
    """
    active_engine = engine or get_db_engine()
    
    # Ensure database tables exist
    Base.metadata.create_all(bind=active_engine)
    factory = session_factory or get_session_factory(engine=active_engine)

    # 1. Load standards from repository if not provided
    if standards is None:
        repo = get_default_repository()
        standards = repo.get_all_standards()

    total_standards = len(standards)
    logger.info(f"Starting embedding seeding for {total_standards} standards...")

    # 2. Filter and validate standard records
    valid_standards: List[Dict[str, Any]] = []
    valid_texts: List[str] = []
    skipped = 0
    failed = 0

    for idx, std in enumerate(standards):
        if not isinstance(std, dict):
            logger.warning(f"Skipping invalid standard item at index {idx}: not a dictionary.")
            failed += 1
            continue

        std_id = std.get("id")
        if not std_id:
            logger.warning(f"Skipping standard item at index {idx}: missing 'id'.")
            skipped += 1
            continue

        content = build_embedding_content(std)
        if not content:
            logger.warning(f"Skipping standard '{std_id}': empty embedding text content.")
            skipped += 1
            continue

        valid_standards.append(std)
        valid_texts.append(content)

    if not valid_standards:
        logger.warning("No valid standards with text content found for embedding population.")
        return {
            "standards_processed": total_standards,
            "valid_standards": 0,
            "embeddings_generated": 0,
            "inserted": 0,
            "updated": 0,
            "skipped": skipped,
            "failed": failed,
            "total_in_db": 0
        }

    # 3. Generate embeddings using existing SemanticEmbeddingEngine
    if embedding_engine is None:
        logger.info(f"Initializing SemanticEmbeddingEngine with model '{DEFAULT_EMBEDDING_MODEL}'...")
        embedding_engine = SemanticEmbeddingEngine(valid_standards, model_name=DEFAULT_EMBEDDING_MODEL)

    model_name = embedding_engine.active_model_name
    dimension = embedding_engine.vector_dimension

    logger.info(f"Generated embeddings for {len(valid_standards)} valid standards. Model='{model_name}', Dimension={dimension}.")

    # 4. Perform idempotent upsert into database table in an atomic session transaction
    session: Session = factory()
    inserted = 0
    updated = 0

    try:
        # Fetch existing embedding records for fast lookup
        existing_rows = session.query(StandardEmbeddingModel).all()
        existing_map = {
            (r.standard_id, r.content, r.embedding_model): r
            for r in existing_rows
        }

        # Verify parent standards exist in DB if using foreign key enforcement
        db_std_ids = {s.id for s in session.query(StandardModel.id).all()}

        for idx, (std, content) in enumerate(zip(valid_standards, valid_texts)):
            std_id = std["id"]

            # If parent standard is missing from DB standards table, create parent record
            if std_id not in db_std_ids:
                logger.info(f"Parent StandardModel '{std_id}' missing in DB table 'standards'. Inserting standard parent record...")
                from backend.retrieval.loader import get_default_repository
                raw_std = get_default_repository().get_standard_by_id(std_id) or std
                if isinstance(raw_std, IndianStandardRecord):
                    std_orm = StandardModel.from_pydantic(raw_std)
                else:
                    std_orm = StandardModel.from_pydantic(IndianStandardRecord(**raw_std))
                session.add(std_orm)
                db_std_ids.add(std_id)

            # Retrieve dense vector embedding from engine
            if embedding_engine.doc_embeddings is not None and idx < len(embedding_engine.doc_embeddings):
                vec_arr = embedding_engine.doc_embeddings[idx]
                vec_list = [float(v) for v in vec_arr]
            else:
                vec_list = []

            # 5. Validate vector dimension
            if len(vec_list) != dimension:
                logger.error(
                    f"Vector dimension mismatch for standard '{std_id}': "
                    f"expected {dimension}, got {len(vec_list)}. Skipping record."
                )
                failed += 1
                continue

            lookup_key = (std_id, content, model_name)
            if lookup_key in existing_map:
                # Update existing embedding record
                existing_orm = existing_map[lookup_key]
                existing_orm.embedding = vec_list
                existing_orm.embedding_dimension = dimension
                updated += 1
            else:
                # Create new embedding record
                new_orm = StandardEmbeddingModel(
                    standard_id=std_id,
                    content=content,
                    embedding=vec_list,
                    embedding_model=model_name,
                    embedding_dimension=dimension
                )
                session.add(new_orm)
                existing_map[lookup_key] = new_orm
                inserted += 1

        # Commit transaction atomically
        session.commit()
        total_in_db = session.query(StandardEmbeddingModel).count()

        summary = {
            "standards_processed": total_standards,
            "valid_standards": len(valid_standards),
            "embeddings_generated": len(valid_standards),
            "inserted": inserted,
            "updated": updated,
            "skipped": skipped,
            "failed": failed,
            "total_in_db": total_in_db
        }
        logger.info(f"Embedding population completed successfully: {summary}")
        return summary

    except Exception as e:
        logger.error(f"Error populating standard_embeddings table. Rolling back transaction: {e}")
        session.rollback()
        raise
    finally:
        session.close()


def main():
    """
    CLI Entry point for explicit PostgreSQL standard embedding population.

    Usage:
        python -m backend.database.seed_embeddings
    """
    logger.info("Executing database embedding population CLI...")
    try:
        engine = get_db_engine(force_new=True)

        # Connection check: fail immediately without fallback if PostgreSQL/DB is unreachable
        if not check_database_connection(engine):
            logger.error(f"Database connection failed. Embedding population aborted.")
            print(f"ERROR: Database connection failed. Ensure PostgreSQL server is running.", file=sys.stderr)
            sys.exit(1)
    except Exception as e:
        logger.error(f"Database connection setup failed: {e}")
        print(f"ERROR: Database connection failed: {e}", file=sys.stderr)
        sys.exit(1)

    try:
        summary = seed_embeddings(engine=engine)
        print(f"SUCCESS: Standard embeddings database population completed. Stats: {summary}")
        sys.exit(0)
    except Exception as e:
        logger.error(f"Embedding population failed with error: {e}", exc_info=True)
        print(f"ERROR: Embedding population failed: {e}", file=sys.stderr)
        sys.exit(1)



if __name__ == "__main__":
    main()
